spring.application.name=jello_app

spring.datasource.url=jdbc:postgresql://localhost:5432/jello_app
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

## FLYWAY PROPERTIES
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
## spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
logging.level.org.flywaydb=DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

auth.token.jwtSecret=t8QzvF3l9GmPq4RkX2y7HjVw6sZbN1uA0eYpLqTcRfUiMvWx
auth.token.expirationInMils=3600000

api.prefix=/api/v1

frontend.url=http://localhost:5173