CREATE TABLE public.follows
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT    NOT NULL,
    following_id BIGINT    NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_follower
        FOREIGN KEY (follower_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_following
        FOREIGN KEY (following_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT unique_follow_relationship
        UNIQUE (follower_id, following_id),

    CONSTRAINT check_self_follow
        CHECK (follower_id <> following_id)
);