CREATE TABLE public.images
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    file_name VARCHAR(255),
    file_type VARCHAR(255),
    download_url VARCHAR(255),
    image BYTEA,
    CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);